language: smalltalk
sudo: false

os:
  - linux

addons:
  ssh_known_hosts: ccmi.fit.cvut.cz

env:
  global:
    - ARTIFACT_DIR=openponk-image-$TRAVIS_BUILD_NUMBER
    - KEY=.ssh/id_openponk_travis

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache

#smalltalk_edge:
#  source: peteruhnak/smalltalkCI
#  branch: iceberg-loading

smalltalk:
  - Pharo-6.1

before_install:
  - openssl aes-256-cbc -K $encrypted_be80011f599c_key -iv $encrypted_be80011f599c_iv -in $KEY.enc -out $KEY -d
  - chmod 0400 $KEY
  - eval $(ssh-agent -s)
  - ssh-add $KEY

after_success:
  - ./scripts/copy-image.sh $SMALLTALK_CI_IMAGE $ARTIFACT_DIR/openponk
  - ./scripts/mark-image.sh $ARTIFACT_DIR/openponk

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
