language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

before_install:
  - openssl aes-256-cbc -K $encrypted_cacb30fd339e_key -iv $encrypted_cacb30fd339e_iv -in .ssh/id_dynacase_travis.enc -out .ssh/id_dynacase_travis -d
  - chmod 0400 .ssh/id_dynacase_travis

before_script:
  - echo -e "Host ccmi.fit.cvut.cz\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
  - tar czf dynacase.tar.gz $TRAVIS_BUILD_DIR
  - scp -i .ssh/id_dynacase_travis -rp dynacase.tar.gz dynacase@ccmi.fit.cvut.cz:~/builds/
