language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal
  ssh_known_hosts: ccmi.fit.cvut.cz

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

#before_install:
#  - openssl aes-256-cbc -K $encrypted_cacb30fd339e_key -iv $encrypted_cacb30fd339e_iv -in .ssh/id_dynacase_travis.enc -out .ssh/id_dynacase_travis -d
#  - chmod 0400 .ssh/id_dynacase_travis
#  - eval $(ssh-agent -s)
#  - ssh-add .ssh/id_dynacase_travis

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: scripts/deploy.sh

#after_success:
#  - ./scripts/coverage.sh
