language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

before_install:
  - openssl aes-256-cbc -K $encrypted_300117cd6c66_key -iv $encrypted_300117cd6c66_iv -in id_dynacase_travis.enc -out id_dynacase_travis -d
