language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal
  ssh_known_hosts: ccmi.fit.cvut.cz

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-6.0

before_install:
  - openssl aes-256-cbc -K $encrypted_fefa832a4450_key -iv $encrypted_fefa832a4450_iv -in .ssh/id_openponk_travis.enc -out .ssh/id_openponk_travis -d
  - chmod 0400 .ssh/id_openponk_travis
  - eval $(ssh-agent -s)
  - ssh-add .ssh/id_openponk_travis

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh

after_success:
  - ./scripts/pre-deploy.sh
  - ./scripts/coverage.sh
