language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libcairo2:i386 # install cairo for Roassal

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

before_install:
  - openssl aes-256-cbc -K $encrypted_cacb30fd339e_key -iv $encrypted_cacb30fd339e_iv -in .ssh/id_dynacase_travis.enc -out .ssh/id_dynacase_travis -d

after_success:
  scp -rp $TRAVIS_BUILD_DIR dynacase@ccmi.fit.cvut.cz:~/builds/
